"""Curated SAP IS-U topic catalog for automatic research runs."""
from dataclasses import dataclass


@dataclass(frozen=True)
class TopicDefinition:
    id: str
    category: str
    label: str
    topic: str
    source_ids: tuple[str, ...]
    objects: tuple[str, ...]
    seed_text: str


TECH_SOURCES = ("sap-datasheet", "leanx", "tcodesearch", "se80")
OFFICIAL_SOURCES = ("sap-help", "sap-learning", "sap-business-accelerator-hub")
MAKO_SOURCES = ("bdew-edi-energy", "sap-help", "sap-datasheet", "tcodesearch")
COUNTRY_SOURCES = ("cnmc-spain", "uregni-retail", "ireland-rmd", "cre-france", "sap-help")


CURATED_TOPIC_CATALOG: tuple[TopicDefinition, ...] = (
    TopicDefinition(
        "md-business-partner-contract-account",
        "Master Data",
        "Business Partner / Contract Account",
        "SAP IS-U business partner contract account FKKVKP BUT000",
        TECH_SOURCES + ("sap-help",),
        ("FKKVKP", "BUT000"),
        "SAP IS-U customer analysis often connects business partner master data in BUT000 with FI-CA contract account partner data in FKKVKP. This topic is useful for move-in, account assignment, correspondence, payment and customer master consistency incidents.",
    ),
    TopicDefinition(
        "md-contract-ever",
        "Master Data",
        "Utility Contract EVER",
        "SAP IS-U utility contract EVER move-in move-out",
        TECH_SOURCES + ("sap-help",),
        ("EVER", "EANL", "FKKVKP"),
        "EVER is a core utility contract object. It is checked in move-in, move-out, billing eligibility, contract account linkage, installation allocation and customer lifecycle incidents.",
    ),
    TopicDefinition(
        "md-installation-eanl",
        "Master Data",
        "Installation EANL",
        "SAP IS-U installation master data EANL EVBS",
        TECH_SOURCES + ("sap-help",),
        ("EANL", "EVBS", "EVER"),
        "EANL represents installation master data and is central to premise, device, meter reading and billing analysis. It is frequently reviewed with premise EVBS and contract EVER.",
    ),
    TopicDefinition(
        "md-premise-pod",
        "Master Data",
        "Premise / POD",
        "SAP IS-U premise point of delivery EVBS EUIHEAD EUIL",
        TECH_SOURCES + ("sap-help",),
        ("EVBS", "EUIHEAD", "EUILO", "EANL"),
        "Premise and point of delivery analysis links EVBS, EUIHEAD/EUILO and installation data. This matters for market communication, address, POD, move-in and allocation incidents.",
    ),
    TopicDefinition(
        "device-equipment",
        "Device Management",
        "Equipment / Device",
        "SAP IS-U device equipment EQUI device management",
        TECH_SOURCES + ("sap-help",),
        ("EQUI", "EGERH"),
        "Device management incidents often start from equipment EQUI and device history EGERH to confirm device identity, validity periods, installation status and replacement history.",
    ),
    TopicDefinition(
        "device-history-egerh",
        "Device Management",
        "Device History EGERH",
        "SAP IS-U device installation removal EGERH EASTL",
        TECH_SOURCES + ("sap-help",),
        ("EGERH", "EASTL", "EQUI"),
        "EGERH and EASTL are relevant when validating device installation/removal, register allocation, date intervals and billing-period consistency.",
    ),
    TopicDefinition(
        "device-register-etdz",
        "Device Management",
        "Registers / Device Facts ETDZ",
        "SAP IS-U register device facts ETDZ EASTL",
        TECH_SOURCES + ("sap-help",),
        ("ETDZ", "EASTL", "EGERH"),
        "Register and device fact analysis is useful for meter reading channels, billing-relevant registers, replacement scenarios and mixed-register incidents.",
    ),
    TopicDefinition(
        "mr-results-eabl",
        "Meter Reading",
        "Meter Reading Results EABL",
        "SAP IS-U meter reading EABL EABLG",
        TECH_SOURCES + ("sap-help",),
        ("EABL", "EABLG"),
        "EABL/EABLG are used for meter reading result analysis, validation, estimated values, missing readings and billing input troubleshooting.",
    ),
    TopicDefinition(
        "mr-orders-el31",
        "Meter Reading",
        "Meter Reading Orders EL31",
        "SAP IS-U meter reading order EL31 EL28",
        TECH_SOURCES + ("sap-help",),
        ("EL31", "EL28", "EABL"),
        "Meter reading order topics cover creation, scheduling, entry, validation and follow-up of readings before billing.",
    ),
    TopicDefinition(
        "mr-validation-estimation",
        "Meter Reading",
        "Validation / Estimation",
        "SAP IS-U meter reading validation estimation EABL",
        TECH_SOURCES + ("sap-help",),
        ("EABL", "EABLG", "EL31"),
        "Validation and estimation incidents involve plausibility checks, estimated meter readings, tolerance rules and downstream billing impact.",
    ),
    TopicDefinition(
        "billing-erch",
        "Billing",
        "Billing Document ERCH",
        "SAP IS-U billing document ERCH EA00 EA19",
        TECH_SOURCES + ("sap-help",),
        ("ERCH", "EA00", "EA19"),
        "ERCH billing document analysis supports billing simulation, actual billing, rate determination and error triage in EA00/EA19 scenarios.",
    ),
    TopicDefinition(
        "billing-invoice-erdk",
        "Billing",
        "Invoicing Document ERDK",
        "SAP IS-U invoicing document ERDK print document",
        TECH_SOURCES + ("sap-help",),
        ("ERDK", "ERCH"),
        "ERDK is relevant for invoicing, print documents, FI-CA posting, invoice reversal and billing-to-invoicing reconciliation.",
    ),
    TopicDefinition(
        "billing-rate-schema",
        "Billing",
        "Rates / Schema / Operands",
        "SAP IS-U billing schema rate category price operands TE420 TE422",
        TECH_SOURCES + ("sap-help",),
        ("TE420", "TE422", "ERCH"),
        "Rate and schema analysis covers operands, rate categories, billing schema configuration, price determination and billing discrepancies.",
    ),
    TopicDefinition(
        "billing-simulation",
        "Billing",
        "Billing Simulation",
        "SAP IS-U billing simulation EA00 EA19 ERCH",
        TECH_SOURCES + ("sap-help",),
        ("EA00", "EA19", "ERCH", "EABL"),
        "Billing simulation topics are useful for comparing expected/actual billing, checking meter reading input, rate determination and schema execution.",
    ),
    TopicDefinition(
        "fica-open-items",
        "FI-CA",
        "Open Items DFKKOP",
        "SAP FI-CA open items DFKKOP FPL9",
        TECH_SOURCES + ("sap-help",),
        ("DFKKOP", "FPL9", "FKKVKP"),
        "FI-CA open item analysis uses DFKKOP and account display transactions such as FPL9 to investigate balances, clearing, payments and dunning.",
    ),
    TopicDefinition(
        "fica-payments-clearing",
        "FI-CA",
        "Payments / Clearing",
        "SAP FI-CA payments clearing FPCJ FP03 DFKKOP",
        TECH_SOURCES + ("sap-help",),
        ("FPCJ", "FP03", "DFKKOP"),
        "Payments and clearing topics cover cash desk, payment allocation, clearing restrictions, contract account balances and posting analysis.",
    ),
    TopicDefinition(
        "fica-dunning",
        "FI-CA",
        "Dunning",
        "SAP FI-CA dunning contract account DFKKOP",
        TECH_SOURCES + ("sap-help",),
        ("DFKKOP", "FKKVKP"),
        "Dunning incidents involve overdue open items, dunning procedure, locks, correspondence and contract account configuration.",
    ),
    TopicDefinition(
        "move-in",
        "Move-In/Out",
        "Move-In",
        "SAP IS-U move-in business partner contract installation EVER EANL",
        TECH_SOURCES + ("sap-help",),
        ("EVER", "EANL", "FKKVKP", "BUT000"),
        "Move-in analysis links business partner, contract account, installation and contract creation. It is important for customer onboarding and billing start issues.",
    ),
    TopicDefinition(
        "move-out",
        "Move-In/Out",
        "Move-Out",
        "SAP IS-U move-out contract termination meter reading EVER EABL",
        TECH_SOURCES + ("sap-help",),
        ("EVER", "EABL", "ERCH"),
        "Move-out analysis covers contract termination, final meter reading, final billing and account balance impacts.",
    ),
    TopicDefinition(
        "idoc-status-edids",
        "IDoc / IDE",
        "IDoc Status EDIDS",
        "SAP IS-U IDoc status EDIDS EDIDC EDID4",
        TECH_SOURCES + ("sap-help",),
        ("EDIDS", "EDIDC", "EDID4"),
        "IDoc troubleshooting uses EDIDS, EDIDC and EDID4 to analyze status, control records, payload and application errors.",
    ),
    TopicDefinition(
        "mako-utilmd",
        "MaKo / EDIFACT",
        "UTILMD",
        "SAP IS-U UTILMD IDoc EDIDS GPKE",
        MAKO_SOURCES,
        ("UTILMD", "EDIDS", "EDIDC", "APERAK"),
        "UTILMD is a key German market communication message for master data and process exchanges. SAP IS-U analysis often connects UTILMD to IDoc status, APERAK and GPKE/WiM rules.",
    ),
    TopicDefinition(
        "mako-mscons",
        "MaKo / EDIFACT",
        "MSCONS",
        "SAP IS-U MSCONS meter reading IDoc EDIDS",
        MAKO_SOURCES,
        ("MSCONS", "EDIDS", "EABL"),
        "MSCONS is used for consumption and meter reading value communication. It connects market communication with meter reading results and IDoc processing.",
    ),
    TopicDefinition(
        "mako-aperak",
        "MaKo / EDIFACT",
        "APERAK",
        "SAP IS-U APERAK error handling UTILMD MSCONS",
        MAKO_SOURCES,
        ("APERAK", "UTILMD", "MSCONS", "EDIDS"),
        "APERAK application acknowledgements are analyzed when market communication messages are rejected or accepted with application-level feedback.",
    ),
    TopicDefinition(
        "mako-gpke",
        "MaKo / EDIFACT",
        "GPKE",
        "SAP IS-U GPKE market communication UTILMD",
        MAKO_SOURCES,
        ("GPKE", "UTILMD", "APERAK"),
        "GPKE governs German electricity market communication processes and is relevant for supplier switch, master data exchange and UTILMD-related incidents.",
    ),
    TopicDefinition(
        "mako-wim-mabis",
        "MaKo / EDIFACT",
        "WiM / MaBiS",
        "SAP IS-U WiM MaBiS EDIFACT MSCONS UTILMD",
        MAKO_SOURCES,
        ("WIM", "MABIS", "MSCONS", "UTILMD"),
        "WiM and MaBiS topics are relevant for metering processes, balancing, consumption value communication and German market process compliance.",
    ),
)


SCOUT_TOPIC_CATALOG: tuple[TopicDefinition, ...] = (
    TopicDefinition(
        "scout-table-dfkkop",
        "FI-CA",
        "DFKKOP Open Item Table",
        "SAP FI-CA table DFKKOP open items clearing dunning",
        TECH_SOURCES + ("sap-help",),
        ("DFKKOP", "FKKVKP", "FPL9"),
        "DFKKOP is a key FI-CA table for open item analysis. Use it for balances, clearing, dunning, payment allocation and contract account incident triage.",
    ),
    TopicDefinition(
        "scout-table-dfkkko",
        "FI-CA",
        "DFKKKO Document Header",
        "SAP FI-CA table DFKKKO document header posting",
        TECH_SOURCES + ("sap-help",),
        ("DFKKKO", "DFKKOP", "FP03"),
        "DFKKKO stores FI-CA document header context and is useful when reconciling postings, document numbers, open item lines and invoicing transfers.",
    ),
    TopicDefinition(
        "scout-table-dfkkopk",
        "FI-CA",
        "DFKKOPK G/L Items",
        "SAP FI-CA table DFKKOPK general ledger items",
        TECH_SOURCES + ("sap-help",),
        ("DFKKOPK", "DFKKKO", "DFKKOP"),
        "DFKKOPK is relevant for FI-CA general ledger item analysis, reconciliation questions and posting transfer incidents.",
    ),
    TopicDefinition(
        "scout-table-dfkklocks",
        "FI-CA",
        "FI-CA Locks",
        "SAP FI-CA locks DFKKLOCKS dunning payment clearing",
        TECH_SOURCES + ("sap-help",),
        ("DFKKLOCKS", "DFKKOP", "FKKVKP"),
        "FI-CA locks can block dunning, payment, clearing or billing follow-up steps. The topic supports analysis of lock reason, validity and affected contract accounts.",
    ),
    TopicDefinition(
        "scout-tcode-fpl9",
        "FI-CA",
        "FPL9 Account Display",
        "SAP FI-CA transaction FPL9 contract account display open items",
        TECH_SOURCES + ("sap-help",),
        ("FPL9", "DFKKOP", "FKKVKP"),
        "FPL9 is a FI-CA transaction used to inspect contract account balances, open items, clearing state and customer account history.",
    ),
    TopicDefinition(
        "scout-tcode-fp03",
        "FI-CA",
        "FP03 FI-CA Document Display",
        "SAP FI-CA transaction FP03 document display DFKKKO DFKKOP",
        TECH_SOURCES + ("sap-help",),
        ("FP03", "DFKKKO", "DFKKOP"),
        "FP03 is useful for investigating FI-CA document headers, item lines, clearing references and posting details.",
    ),
    TopicDefinition(
        "scout-tcode-fp05",
        "FI-CA",
        "FP05 Incoming Payment Lot",
        "SAP FI-CA transaction FP05 payment lot incoming payments",
        TECH_SOURCES + ("sap-help",),
        ("FP05", "DFKKOP"),
        "FP05 payment lot topics support incidents around incoming payment allocation, payment medium import and posting status.",
    ),
    TopicDefinition(
        "scout-tcode-fp06",
        "FI-CA",
        "FP06 Payment Lot Processing",
        "SAP FI-CA transaction FP06 payment lot processing clearing",
        TECH_SOURCES + ("sap-help",),
        ("FP06", "DFKKOP"),
        "FP06 is relevant for payment lot processing, clarification and clearing follow-up incidents.",
    ),
    TopicDefinition(
        "scout-tcode-fpcj",
        "FI-CA",
        "FPCJ Cash Desk",
        "SAP FI-CA transaction FPCJ cash desk payment",
        TECH_SOURCES + ("sap-help",),
        ("FPCJ", "DFKKOP"),
        "FPCJ supports cash desk payment analysis, cash journal postings and customer payment troubleshooting.",
    ),
    TopicDefinition(
        "scout-table-euitrans",
        "Master Data",
        "POD External IDs",
        "SAP IS-U point of delivery external ID EUIHEAD EUITRANS",
        TECH_SOURCES + ("sap-help",),
        ("EUIHEAD", "EUITRANS", "EUILO"),
        "Point of delivery external identification topics help analyze MaLo/POD mapping, external IDs, address allocation and market communication references.",
    ),
    TopicDefinition(
        "scout-table-euiinstln",
        "Master Data",
        "POD Installation Allocation",
        "SAP IS-U point of delivery installation allocation EUIINSTLN EANL",
        TECH_SOURCES + ("sap-help",),
        ("EUIINSTLN", "EUIHEAD", "EANL"),
        "POD-to-installation allocation is relevant for contract, meter reading, billing and market communication consistency checks.",
    ),
    TopicDefinition(
        "scout-table-iflot",
        "Device Management",
        "Functional Location IFLOT",
        "SAP IS-U functional location IFLOT device premise allocation",
        TECH_SOURCES + ("sap-help",),
        ("IFLOT", "EQUI", "EVBS"),
        "IFLOT can be useful when device or technical-location allocation is involved in utilities incidents.",
    ),
    TopicDefinition(
        "scout-table-equz",
        "Device Management",
        "Equipment Time Segment EQUZ",
        "SAP equipment table EQUZ device time segment EQUI EGERH",
        TECH_SOURCES + ("sap-help",),
        ("EQUZ", "EQUI", "EGERH"),
        "EQUZ supports time-dependent equipment assignment analysis, especially around device replacement and validity intervals.",
    ),
    TopicDefinition(
        "scout-table-eger",
        "Device Management",
        "Device Master EGER",
        "SAP IS-U table EGER device master data",
        TECH_SOURCES + ("sap-help",),
        ("EGER", "EGERH", "EQUI"),
        "EGER device master data is useful for device category, serial number and device identity troubleshooting.",
    ),
    TopicDefinition(
        "scout-table-egerr",
        "Device Management",
        "Device Register EGERR",
        "SAP IS-U table EGERR device register facts",
        TECH_SOURCES + ("sap-help",),
        ("EGERR", "ETDZ", "EASTL"),
        "Device register data is relevant for register allocation, meter reading channels and billing-relevant measurement points.",
    ),
    TopicDefinition(
        "scout-tcode-iq03",
        "Device Management",
        "IQ03 Equipment Display",
        "SAP transaction IQ03 equipment display device EQUI",
        TECH_SOURCES + ("sap-help",),
        ("IQ03", "EQUI", "EGERH"),
        "IQ03 is commonly used to inspect equipment master data and validate device identity during incident analysis.",
    ),
    TopicDefinition(
        "scout-tcode-es31",
        "Device Management",
        "ES31 Device Display",
        "SAP IS-U transaction ES31 device display EGERH",
        TECH_SOURCES + ("sap-help",),
        ("ES31", "EGERH", "EQUI"),
        "ES31 supports device display and installation history checks in device management incidents.",
    ),
    TopicDefinition(
        "scout-tcode-el01",
        "Meter Reading",
        "EL01 Meter Reading Entry",
        "SAP IS-U transaction EL01 meter reading entry EABL",
        TECH_SOURCES + ("sap-help",),
        ("EL01", "EABL", "EABLG"),
        "EL01 is relevant for entering meter readings and analyzing validation messages or missing result creation.",
    ),
    TopicDefinition(
        "scout-tcode-el28",
        "Meter Reading",
        "EL28 Meter Reading Order",
        "SAP IS-U transaction EL28 meter reading order EABL",
        TECH_SOURCES + ("sap-help",),
        ("EL28", "EABL", "EL31"),
        "EL28 helps with meter reading order display and order-level troubleshooting before readings are posted.",
    ),
    TopicDefinition(
        "scout-tcode-el31",
        "Meter Reading",
        "EL31 Meter Reading Result",
        "SAP IS-U transaction EL31 meter reading result EABL",
        TECH_SOURCES + ("sap-help",),
        ("EL31", "EABL", "EABLG"),
        "EL31 is used for meter reading result display and validation follow-up in SAP IS-U.",
    ),
    TopicDefinition(
        "scout-tcode-el37",
        "Meter Reading",
        "EL37 Mass Meter Reading",
        "SAP IS-U transaction EL37 mass meter reading order",
        TECH_SOURCES + ("sap-help",),
        ("EL37", "EABL", "EL31"),
        "EL37 is useful in mass meter reading order or result processing incidents.",
    ),
    TopicDefinition(
        "scout-table-eablg",
        "Meter Reading",
        "EABLG Reading Details",
        "SAP IS-U table EABLG meter reading detail validation",
        TECH_SOURCES + ("sap-help",),
        ("EABLG", "EABL", "EL31"),
        "EABLG provides detail context for meter reading results, validation and billing input analysis.",
    ),
    TopicDefinition(
        "scout-table-eablh",
        "Meter Reading",
        "EABLH Reading History",
        "SAP IS-U table EABLH meter reading history",
        TECH_SOURCES + ("sap-help",),
        ("EABLH", "EABL", "EABLG"),
        "Meter reading history topics help diagnose repeated readings, reversals, estimations and historical consistency.",
    ),
    TopicDefinition(
        "scout-table-etrg",
        "Billing",
        "Billing Order ETRG",
        "SAP IS-U table ETRG billing order EA00 EA19",
        TECH_SOURCES + ("sap-help",),
        ("ETRG", "EA00", "EA19"),
        "ETRG is relevant for billing order creation, billing due lists and billing execution readiness.",
    ),
    TopicDefinition(
        "scout-table-erchc",
        "Billing",
        "Billing Document Lines ERCHC",
        "SAP IS-U table ERCHC billing document lines ERCH",
        TECH_SOURCES + ("sap-help",),
        ("ERCHC", "ERCH", "EA19"),
        "Billing document line analysis helps explain rate execution, quantities, amounts and schema results.",
    ),
    TopicDefinition(
        "scout-table-dberchz",
        "Billing",
        "Billing Line Items DBERCHZ",
        "SAP IS-U table DBERCHZ billing line items schema",
        TECH_SOURCES + ("sap-help",),
        ("DBERCHZ", "ERCH", "TE422"),
        "DBERCHZ-style billing line item analysis is useful for tracing operands, quantities and price calculation details.",
    ),
    TopicDefinition(
        "scout-tcode-ea00",
        "Billing",
        "EA00 Billing",
        "SAP IS-U transaction EA00 billing execution ERCH",
        TECH_SOURCES + ("sap-help",),
        ("EA00", "ERCH", "ETRG"),
        "EA00 billing execution topics help diagnose billing run failures, missing billing orders and rate determination issues.",
    ),
    TopicDefinition(
        "scout-tcode-ea19",
        "Billing",
        "EA19 Billing Simulation",
        "SAP IS-U transaction EA19 billing simulation ERCH",
        TECH_SOURCES + ("sap-help",),
        ("EA19", "ERCH", "EABL"),
        "EA19 simulation is used to compare expected billing with actual meter reading, schema and price results.",
    ),
    TopicDefinition(
        "scout-tcode-ea26",
        "Billing",
        "EA26 Billing Document Display",
        "SAP IS-U transaction EA26 billing document display ERCH",
        TECH_SOURCES + ("sap-help",),
        ("EA26", "ERCH", "ERCHC"),
        "EA26 supports billing document display and line-level billing explanation during incident analysis.",
    ),
    TopicDefinition(
        "scout-tcode-ea40",
        "Billing",
        "EA40 Billing Reversal",
        "SAP IS-U transaction EA40 billing reversal ERCH",
        TECH_SOURCES + ("sap-help",),
        ("EA40", "ERCH", "ERDK"),
        "EA40 reversal topics are useful for billing/invoicing correction flows and document reversal incidents.",
    ),
    TopicDefinition(
        "scout-table-te417",
        "Billing",
        "Rate Category TE417",
        "SAP IS-U table TE417 rate category billing schema",
        TECH_SOURCES + ("sap-help",),
        ("TE417", "TE420", "TE422"),
        "Rate category configuration is central to billing schema selection and price determination troubleshooting.",
    ),
    TopicDefinition(
        "scout-table-te420",
        "Billing",
        "Billing Schema TE420",
        "SAP IS-U table TE420 billing schema",
        TECH_SOURCES + ("sap-help",),
        ("TE420", "TE422", "ERCH"),
        "TE420-style schema topics support billing rule and schema determination analysis.",
    ),
    TopicDefinition(
        "scout-table-te422",
        "Billing",
        "Rates TE422",
        "SAP IS-U table TE422 rate facts price operands",
        TECH_SOURCES + ("sap-help",),
        ("TE422", "TE420", "ERCH"),
        "TE422 and related rate facts are relevant for operand, price, quantity and billing amount investigations.",
    ),
    TopicDefinition(
        "scout-tcode-we02",
        "IDoc / IDE",
        "WE02 IDoc Display",
        "SAP transaction WE02 IDoc display EDIDC EDIDS EDID4",
        TECH_SOURCES + ("sap-help",),
        ("WE02", "EDIDC", "EDIDS", "EDID4"),
        "WE02 is used for IDoc display and supports status, control record and payload checks in market communication incidents.",
    ),
    TopicDefinition(
        "scout-tcode-bd87",
        "IDoc / IDE",
        "BD87 IDoc Reprocessing",
        "SAP transaction BD87 IDoc reprocessing EDIDS status",
        TECH_SOURCES + ("sap-help",),
        ("BD87", "EDIDS", "EDIDC"),
        "BD87 reprocessing is relevant for retrying failed IDocs and understanding application status recovery.",
    ),
    TopicDefinition(
        "scout-tcode-we19",
        "IDoc / IDE",
        "WE19 IDoc Test Tool",
        "SAP transaction WE19 IDoc test tool EDID4",
        TECH_SOURCES + ("sap-help",),
        ("WE19", "EDIDC", "EDID4"),
        "WE19 is used to test or reproduce IDoc processing scenarios in controlled incident analysis.",
    ),
    TopicDefinition(
        "scout-table-edidc",
        "IDoc / IDE",
        "EDIDC Control Record",
        "SAP table EDIDC IDoc control record",
        TECH_SOURCES + ("sap-help",),
        ("EDIDC", "EDIDS", "EDID4"),
        "EDIDC stores IDoc control records, partner data and message metadata needed for market communication analysis.",
    ),
    TopicDefinition(
        "scout-table-edid4",
        "IDoc / IDE",
        "EDID4 Data Records",
        "SAP table EDID4 IDoc data records segments",
        TECH_SOURCES + ("sap-help",),
        ("EDID4", "EDIDC", "EDIDS"),
        "EDID4 stores IDoc data records and segment payloads used when analyzing UTILMD, MSCONS or APERAK content.",
    ),
    TopicDefinition(
        "scout-table-edpp1",
        "IDoc / IDE",
        "IDoc Partner Profile",
        "SAP IDoc partner profile WE20 EDPP1 EDIDC",
        TECH_SOURCES + ("sap-help",),
        ("WE20", "EDIDC"),
        "Partner profile topics support incidents around sender/receiver configuration, message type routing and IDoc processing setup.",
    ),
    TopicDefinition(
        "scout-mako-invoic",
        "MaKo / EDIFACT",
        "INVOIC",
        "SAP IS-U INVOIC EDIFACT invoice message IDoc",
        MAKO_SOURCES,
        ("INVOIC", "EDIDS", "EDIDC"),
        "INVOIC market message topics support invoice exchange, IDoc status checks and EDIFACT payload validation.",
    ),
    TopicDefinition(
        "scout-mako-remadv",
        "MaKo / EDIFACT",
        "REMADV",
        "SAP IS-U REMADV EDIFACT remittance advice IDoc",
        MAKO_SOURCES,
        ("REMADV", "EDIDS", "EDIDC"),
        "REMADV is relevant for remittance advice processing, payment allocation and market communication reconciliation.",
    ),
    TopicDefinition(
        "scout-mako-contrl",
        "MaKo / EDIFACT",
        "CONTRL",
        "SAP IS-U CONTRL EDIFACT syntax acknowledgement",
        MAKO_SOURCES,
        ("CONTRL", "UTILMD", "MSCONS", "APERAK"),
        "CONTRL acknowledgements help distinguish syntax-level EDIFACT issues from application-level APERAK rejections.",
    ),
    TopicDefinition(
        "scout-mako-geli-gas",
        "MaKo / EDIFACT",
        "GeLi Gas",
        "SAP IS-U GeLi Gas market process UTILMD APERAK",
        MAKO_SOURCES,
        ("GELI", "UTILMD", "APERAK"),
        "GeLi Gas topics cover German gas market communication processes and message-level troubleshooting.",
    ),
    TopicDefinition(
        "scout-mako-mpes",
        "MaKo / EDIFACT",
        "MPES",
        "SAP IS-U MPES market process EDIFACT MSCONS",
        MAKO_SOURCES,
        ("MPES", "MSCONS", "UTILMD"),
        "MPES topics are useful for German market process analysis where EDIFACT message rules and process deadlines matter.",
    ),
    TopicDefinition(
        "scout-mako-gabi-gas",
        "MaKo / EDIFACT",
        "GABi Gas",
        "SAP IS-U GABi Gas balancing market communication",
        MAKO_SOURCES,
        ("GABI", "MSCONS", "UTILMD"),
        "GABi Gas topics support gas balancing and consumption value communication context for utilities incidents.",
    ),
    TopicDefinition(
        "scout-ide-eideswtdoc",
        "MaKo / EDIFACT",
        "Switch Document",
        "SAP IS-U IDE switch document EIDESWTDOC UTILMD",
        MAKO_SOURCES,
        ("EIDESWTDOC", "UTILMD", "APERAK"),
        "Switch document analysis links market process state, UTILMD exchange and supplier-switch incident handling.",
    ),
    TopicDefinition(
        "scout-ide-edextask",
        "MaKo / EDIFACT",
        "IDE Task Processing",
        "SAP IS-U IDE task processing EDEXTASK EDIFACT",
        MAKO_SOURCES,
        ("EDEXTASK", "EDIDS", "UTILMD"),
        "IDE task processing topics help track technical market communication jobs, status transitions and failed message handling.",
    ),
    TopicDefinition(
        "scout-ide-edexproc",
        "MaKo / EDIFACT",
        "IDE Process State",
        "SAP IS-U IDE process EDEXPROC market communication",
        MAKO_SOURCES,
        ("EDEXPROC", "UTILMD", "MSCONS"),
        "IDE process state topics support analysis of market communication process orchestration and state mismatches.",
    ),
    TopicDefinition(
        "scout-move-in-ec50e",
        "Move-In/Out",
        "EC50E Move-In/Out Workbench",
        "SAP IS-U transaction EC50E move-in move-out contract",
        TECH_SOURCES + ("sap-help",),
        ("EC50E", "EVER", "EANL"),
        "Move-in/out workbench topics connect customer lifecycle actions with contract, installation and final billing checks.",
    ),
    TopicDefinition(
        "scout-move-final-billing",
        "Move-In/Out",
        "Final Billing",
        "SAP IS-U final billing move-out EABL ERCH ERDK",
        TECH_SOURCES + ("sap-help",),
        ("EABL", "ERCH", "ERDK", "EVER"),
        "Final billing analysis covers move-out meter reading, billing, invoicing and FI-CA balance impacts.",
    ),
    TopicDefinition(
        "scout-bpem-emma",
        "Exceptions / BPEM",
        "BPEM / EMMA Cases",
        "SAP IS-U BPEM EMMA exception management case",
        TECH_SOURCES + ("sap-help",),
        ("EMMA", "BPEM"),
        "BPEM/EMMA topics support exception management, clarification cases and repeatable incident classification.",
    ),
    TopicDefinition(
        "scout-bpem-case-search",
        "Exceptions / BPEM",
        "Clarification Case Search",
        "SAP IS-U clarification case search EMMA BPEM",
        TECH_SOURCES + ("sap-help",),
        ("EMMA", "BPEM"),
        "Clarification case search topics help tie operational exceptions to underlying SAP objects and resolutions.",
    ),
    TopicDefinition(
        "scout-api-s4-utilities",
        "APIs / Integration",
        "S/4HANA Utilities APIs",
        "SAP Business Accelerator Hub S/4HANA Utilities API contract account billing",
        OFFICIAL_SOURCES,
        ("API", "S4HANA"),
        "S/4HANA Utilities API topics cover modern service integration, business objects and BTP-facing utilities scenarios.",
    ),
    TopicDefinition(
        "scout-api-meter-reading",
        "APIs / Integration",
        "Meter Reading APIs",
        "SAP Utilities API meter reading device installation",
        OFFICIAL_SOURCES,
        ("API", "EABL", "EGERH"),
        "Meter reading API topics are relevant for integration scenarios around readings, devices and external channels.",
    ),
    TopicDefinition(
        "scout-fiori-utilities",
        "Fiori / S/4HANA",
        "Utilities Fiori Apps",
        "SAP S/4HANA Utilities Fiori apps meter to cash",
        OFFICIAL_SOURCES,
        ("FIORI", "S4HANA"),
        "Utilities Fiori topics support modern UI process mapping and app-level troubleshooting.",
    ),
    TopicDefinition(
        "scout-s4-utilities-migration",
        "Fiori / S/4HANA",
        "S/4HANA Utilities Migration",
        "SAP S/4HANA Utilities migration IS-U simplification",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "ISU"),
        "S/4HANA Utilities migration topics help distinguish legacy IS-U behavior from S/4HANA-specific integration, UI and data model changes.",
    ),
)


def _expert_topic(
    suffix: str,
    category: str,
    label: str,
    topic: str,
    source_ids: tuple[str, ...],
    objects: tuple[str, ...],
    seed_text: str,
) -> TopicDefinition:
    return TopicDefinition(
        f"expert-{suffix}",
        category,
        label,
        topic,
        source_ids,
        objects,
        seed_text,
    )


EXPERTISE_TOPIC_CATALOG: tuple[TopicDefinition, ...] = (
    _expert_topic(
        "nav-customer-interaction-center",
        "Transactions / Navigation",
        "Customer Interaction Center Navigation",
        "SAP IS-U customer interaction center CIC0 contract account premise navigation",
        TECH_SOURCES + ("sap-help",),
        ("CIC0", "BP", "FKKVKP", "EVER"),
        "CIC0-style front office navigation is useful for moving from customer context to business partner, contract account, contract, premise, installation, billing and FI-CA views during incident triage.",
    ),
    _expert_topic(
        "nav-contract-account-caa",
        "Transactions / Navigation",
        "Contract Account Navigation CAA1 CAA2 CAA3",
        "SAP FI-CA contract account transactions CAA1 CAA2 CAA3 FKKVKP",
        TECH_SOURCES + ("sap-help",),
        ("CAA1", "CAA2", "CAA3", "FKKVKP"),
        "Contract account navigation topics cover create, change, display and related balance checks. They help connect FI-CA account master data with open items, locks, payment methods and utilities contracts.",
    ),
    _expert_topic(
        "nav-business-partner-fpp",
        "Transactions / Navigation",
        "Business Partner / FI-CA Partner Navigation",
        "SAP business partner FI-CA transactions BP FPP1 FPP2 FPP3",
        TECH_SOURCES + ("sap-help",),
        ("BP", "FPP1", "FPP2", "FPP3", "BUT000"),
        "Business partner and FI-CA partner navigation supports incidents where customer identity, contract account assignment, correspondence data or payment responsibility must be verified.",
    ),
    _expert_topic(
        "nav-payment-run-fp04",
        "Transactions / Navigation",
        "Payment Run FP04",
        "SAP FI-CA transaction FP04 payment run DFKKOP clearing",
        TECH_SOURCES + ("sap-help",),
        ("FP04", "DFKKOP", "DFKKOPK"),
        "FP04 payment run topics support troubleshooting around payment proposal, bank collection, clearing state, payment locks and rejected payment items.",
    ),
    _expert_topic(
        "nav-dunning-fpva",
        "Transactions / Navigation",
        "Dunning Proposal FPVA",
        "SAP FI-CA transaction FPVA dunning proposal contract account DFKKOP",
        TECH_SOURCES + ("sap-help",),
        ("FPVA", "DFKKOP", "FKKVKP"),
        "Dunning proposal navigation is useful when checking overdue open items, dunning locks, contract account procedure, correspondence and follow-up actions.",
    ),
    _expert_topic(
        "nav-installation-premise",
        "Transactions / Navigation",
        "Installation and Premise Navigation",
        "SAP IS-U installation premise transactions ES32 ES55 EANL EVBS",
        TECH_SOURCES + ("sap-help",),
        ("ES32", "ES55", "EANL", "EVBS"),
        "Installation and premise navigation connects technical master data, point of delivery, device allocation, meter reading units, billing facts and address context.",
    ),
    _expert_topic(
        "nav-idoc-reprocessing",
        "Transactions / Navigation",
        "IDoc Display and Reprocessing",
        "SAP IDoc navigation WE02 WE05 BD87 WE19 EDIDS EDIDC EDID4",
        TECH_SOURCES + ("sap-help",),
        ("WE02", "WE05", "BD87", "WE19", "EDIDS", "EDIDC", "EDID4"),
        "IDoc navigation topics cover display, status interpretation, payload inspection, test reproduction and controlled reprocessing for UTILMD, MSCONS, APERAK and related market communication messages.",
    ),
    _expert_topic(
        "customizing-spro-overview",
        "Customizing / SPRO",
        "SPRO Utilities Customizing Overview",
        "SAP IS-U customizing SPRO utilities basic settings meter to cash",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "SM30", "ISU"),
        "SPRO Utilities customizing topics map functional configuration areas to practical incident analysis. They are useful for identifying whether behavior is driven by master data, rates, meter reading, billing, FI-CA or market communication configuration.",
    ),
    _expert_topic(
        "customizing-contract-account",
        "Customizing / SPRO",
        "FI-CA Contract Account Customizing",
        "SAP FI-CA customizing contract account account determination payment dunning FKKVKP",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "FKKVKP", "DFKKOP", "SM30"),
        "FI-CA customizing for contract accounts is checked when payment, clearing, dunning, correspondence, account determination or business partner assignment behaves differently than expected.",
    ),
    _expert_topic(
        "customizing-billing-schema",
        "Customizing / SPRO",
        "Billing Schema and Rate Customizing",
        "SAP IS-U customizing billing schema rate category operands TE417 TE420 TE422",
        TECH_SOURCES + ("sap-help",),
        ("SPRO", "TE417", "TE420", "TE422", "ERCH"),
        "Billing schema and rate customizing connects rate category, schema determination, operands, prices and billing document results. It is central for billing variance and simulation incidents.",
    ),
    _expert_topic(
        "customizing-meter-reading",
        "Customizing / SPRO",
        "Meter Reading Validation Customizing",
        "SAP IS-U meter reading customizing validation estimation EABL EABLG",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "EABL", "EABLG", "EL31"),
        "Meter reading customizing topics cover validation, estimation, tolerance checks, order creation and how readings become billing input.",
    ),
    _expert_topic(
        "customizing-device-management",
        "Customizing / SPRO",
        "Device Management Customizing",
        "SAP IS-U device management customizing device category register installation EGERH ETDZ",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "EGERH", "ETDZ", "EASTL", "EQUI"),
        "Device management customizing is useful for incidents involving device categories, register facts, installation/removal, replacement and billing-relevant measurement data.",
    ),
    _expert_topic(
        "customizing-idoc-partner-profile",
        "Customizing / SPRO",
        "IDoc Partner Profile and Port Customizing",
        "SAP IDoc customizing partner profile WE20 WE21 EDIDC EDIDS market communication",
        TECH_SOURCES + ("sap-help",),
        ("WE20", "WE21", "EDIDC", "EDIDS"),
        "IDoc partner profile and port configuration topics help diagnose sender/receiver, message type, process code, port and routing errors in market communication.",
    ),
    _expert_topic(
        "customizing-bpem-emma",
        "Customizing / SPRO",
        "BPEM / EMMA Customizing",
        "SAP IS-U BPEM EMMA customizing clarification case categories",
        TECH_SOURCES + ("sap-help",),
        ("EMMA", "BPEM", "SPRO"),
        "BPEM/EMMA customizing controls clarification case categories, automatic creation and operational exception handling. It links recurring incidents to configurable case processing.",
    ),
    _expert_topic(
        "messages-idoc-status-51",
        "Messages / Errors",
        "IDoc Status 51 Application Error",
        "SAP IDoc status 51 application error EDIDS WE02 BD87 APERAK UTILMD",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("EDIDS", "WE02", "BD87", "UTILMD", "APERAK"),
        "IDoc status 51 troubleshooting links the failed application step, status record, payload segment, process code and possible reprocessing path.",
    ),
    _expert_topic(
        "messages-idoc-status-64",
        "Messages / Errors",
        "IDoc Status 64 Ready to Be Processed",
        "SAP IDoc status 64 ready to be processed EDIDS background job BD87",
        TECH_SOURCES + ("sap-help",),
        ("EDIDS", "BD87", "WE02"),
        "IDoc status 64 topics help distinguish waiting inbound IDocs, background processing, partner profile setup and manual reprocessing decisions.",
    ),
    _expert_topic(
        "messages-aperak-rejection",
        "Messages / Errors",
        "APERAK Rejection Analysis",
        "SAP IS-U APERAK rejection error code UTILMD MSCONS EDIFACT",
        MAKO_SOURCES,
        ("APERAK", "UTILMD", "MSCONS", "EDIDS"),
        "APERAK rejection analysis connects application acknowledgement reason, original EDIFACT message, IDoc status and market process correction steps.",
    ),
    _expert_topic(
        "messages-billing-errors",
        "Messages / Errors",
        "Billing Error Message Triage",
        "SAP IS-U billing error messages EA00 EA19 ERCH rate schema",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("EA00", "EA19", "ERCH", "TE420", "TE422"),
        "Billing error message topics help connect the displayed message to meter reading input, rate determination, schema execution, operands and reversal/rebill options.",
    ),
    _expert_topic(
        "messages-meter-reading-implausible",
        "Messages / Errors",
        "Meter Reading Implausibility Messages",
        "SAP IS-U meter reading implausible validation message EABL EL31",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("EABL", "EABLG", "EL31"),
        "Implausibility messages are analyzed by checking previous readings, validation rules, estimation, register allocation and billing relevance.",
    ),
    _expert_topic(
        "messages-fica-clearing",
        "Messages / Errors",
        "FI-CA Clearing and Payment Messages",
        "SAP FI-CA error messages clearing payment lot DFKKOP FP05 FP06",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("DFKKOP", "FP05", "FP06", "FPL9"),
        "FI-CA payment and clearing messages usually require checking open item state, clearing restrictions, locks, payment lot status and contract account configuration.",
    ),
    _expert_topic(
        "abap-function-modules",
        "ABAP / Enhancements",
        "IS-U Function Modules",
        "SAP IS-U function modules SE37 billing meter reading move-in device management",
        ("sap-help", "se80", "sap-datasheet", "tcodesearch"),
        ("SE37", "SE80", "ISU"),
        "Function module topics support developer-level incident analysis where a process must be traced through standard APIs, update tasks, database access and enhancement points.",
    ),
    _expert_topic(
        "abap-badis-exits",
        "ABAP / Enhancements",
        "BAdIs and Customer Exits",
        "SAP IS-U BAdI customer exit enhancement spot meter reading billing FI-CA",
        ("sap-help", "se80", "sap-datasheet", "tcodesearch"),
        ("BADI", "SE18", "SE19", "CMOD", "SMOD"),
        "BAdI and exit topics help isolate customer-specific logic from standard SAP behavior, especially when production incidents reproduce only in one client or process variant.",
    ),
    _expert_topic(
        "abap-fica-events",
        "ABAP / Enhancements",
        "FI-CA Events and Enhancement Logic",
        "SAP FI-CA events enhancement function modules FQEVENTS DFKKOP",
        ("sap-help", "se80", "sap-datasheet", "tcodesearch"),
        ("FQEVENTS", "DFKKOP", "FKKVKP", "SE37"),
        "FI-CA event topics connect account processing, payment, clearing, dunning and invoicing transfer behavior with custom function modules and event configuration.",
    ),
    _expert_topic(
        "abap-idoc-processing",
        "ABAP / Enhancements",
        "IDoc Processing Function Modules",
        "SAP IDoc processing function modules WE20 process code EDIDC EDIDS",
        ("sap-help", "se80", "sap-datasheet", "tcodesearch"),
        ("WE20", "EDIDC", "EDIDS", "SE37"),
        "IDoc processing topics cover process code configuration, inbound function module execution, status creation and debugging of failed market communication messages.",
    ),
    _expert_topic(
        "abap-s4-classes",
        "ABAP / Enhancements",
        "S/4HANA Utilities ABAP Classes",
        "SAP S/4HANA Utilities ABAP classes APIs Fiori extensibility",
        ("sap-help", "sap-business-accelerator-hub", "se80"),
        ("SE24", "S4HANA", "API", "FIORI"),
        "S/4HANA Utilities class topics help connect legacy IS-U objects with modern APIs, Fiori apps, CDS views and extensibility patterns.",
    ),
    _expert_topic(
        "runbook-meter-to-cash",
        "Runbooks / Troubleshooting",
        "Meter-to-Cash End-to-End",
        "SAP IS-U meter to cash troubleshooting EABL ERCH ERDK DFKKOP",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("EABL", "ERCH", "ERDK", "DFKKOP"),
        "Meter-to-cash troubleshooting follows reading/order creation, validation, billing, invoicing, FI-CA posting and payment/open-item reconciliation.",
    ),
    _expert_topic(
        "runbook-move-in-to-first-bill",
        "Runbooks / Troubleshooting",
        "Move-In to First Bill",
        "SAP IS-U move-in first bill troubleshooting BUT000 FKKVKP EVER EANL ERCH",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("BUT000", "FKKVKP", "EVER", "EANL", "ERCH"),
        "Move-in to first bill analysis checks business partner, contract account, installation, contract start, device allocation, meter reading availability and billing order creation.",
    ),
    _expert_topic(
        "runbook-device-replacement",
        "Runbooks / Troubleshooting",
        "Device Replacement Troubleshooting",
        "SAP IS-U device replacement troubleshooting EGERH EASTL ETDZ EABL billing",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("EGERH", "EASTL", "ETDZ", "EABL", "ERCH"),
        "Device replacement troubleshooting traces removal/installation validity, register facts, meter reading handover, billing-relevant intervals and downstream billing impact.",
    ),
    _expert_topic(
        "runbook-billing-reversal-rebill",
        "Runbooks / Troubleshooting",
        "Billing Reversal and Rebill",
        "SAP IS-U billing reversal rebill troubleshooting EA40 ERCH ERDK DFKKOP",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("EA40", "ERCH", "ERDK", "DFKKOP"),
        "Billing reversal and rebill topics cover document dependencies, invoicing/FI-CA consequences, corrected readings/rates and verification after rebilling.",
    ),
    _expert_topic(
        "runbook-idoc-aperak",
        "Runbooks / Troubleshooting",
        "IDoc to APERAK End-to-End",
        "SAP IS-U IDoc APERAK end-to-end troubleshooting UTILMD MSCONS EDIDS EDIDC",
        MAKO_SOURCES,
        ("UTILMD", "MSCONS", "APERAK", "EDIDS", "EDIDC"),
        "IDoc to APERAK troubleshooting links inbound/outbound message creation, IDoc status, payload validation, application acknowledgement and corrective market-process actions.",
    ),
    _expert_topic(
        "runbook-pod-malo-mismatch",
        "Runbooks / Troubleshooting",
        "POD / MaLo Mismatch",
        "SAP IS-U POD MaLo mismatch troubleshooting EUIHEAD EUITRANS EUIINSTLN UTILMD",
        MAKO_SOURCES + TECH_SOURCES,
        ("EUIHEAD", "EUITRANS", "EUIINSTLN", "UTILMD"),
        "POD/MaLo mismatch runbooks check external/internal POD identifiers, installation allocation, market communication references and master data correction paths.",
    ),
    _expert_topic(
        "mako-versioned-utilmd",
        "MaKo / EDIFACT Versions",
        "UTILMD Versioned Guides",
        "BDEW EDI@Energy UTILMD version process guide SAP IS-U GPKE",
        MAKO_SOURCES,
        ("UTILMD", "GPKE", "EDIDS"),
        "Versioned UTILMD topics focus on current format guides, change releases, process-specific segments and SAP IS-U impact. Always validate version details against current BDEW/EDI@Energy material.",
    ),
    _expert_topic(
        "mako-versioned-mscons",
        "MaKo / EDIFACT Versions",
        "MSCONS Versioned Guides",
        "BDEW EDI@Energy MSCONS version meter reading consumption values SAP IS-U",
        MAKO_SOURCES,
        ("MSCONS", "EABL", "EDIDS"),
        "Versioned MSCONS topics support consumption value exchange, meter reading payload checks, change releases and downstream SAP IS-U meter reading/billing effects.",
    ),
    _expert_topic(
        "mako-pruefident",
        "MaKo / EDIFACT Versions",
        "Pruefident and Process Identifiers",
        "BDEW EDI@Energy Pruefident process identifiers UTILMD MSCONS APERAK",
        MAKO_SOURCES,
        ("UTILMD", "MSCONS", "APERAK", "EDIDS"),
        "Process identifier topics help connect EDIFACT messages to market process variants, validation rules and APERAK outcomes.",
    ),
    _expert_topic(
        "mako-change-releases",
        "MaKo / EDIFACT Versions",
        "MaKo Change Releases",
        "BDEW EDI@Energy GPKE WiM MaBiS change release SAP IS-U",
        MAKO_SOURCES,
        ("GPKE", "WIM", "MABIS", "UTILMD", "MSCONS"),
        "MaKo change release topics track process/version changes that can affect SAP IS-U mapping, IDoc processing, validation, deadlines and operational troubleshooting.",
    ),
    _expert_topic(
        "s4-fiori-apps",
        "S/4HANA Utilities / Fiori / API",
        "S/4HANA Utilities Fiori App Troubleshooting",
        "SAP S/4HANA Utilities Fiori apps troubleshooting meter to cash contract account",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "FIORI", "API"),
        "Fiori app troubleshooting topics connect app intent/navigation, backend authorization, OData/API calls, business object state and legacy IS-U data.",
    ),
    _expert_topic(
        "s4-utilities-apis",
        "S/4HANA Utilities / Fiori / API",
        "Utilities APIs on Business Accelerator Hub",
        "SAP Business Accelerator Hub S/4HANA Utilities APIs contract account meter reading billing",
        OFFICIAL_SOURCES,
        ("API", "S4HANA", "EABL", "FKKVKP", "ERCH"),
        "Utilities API topics cover official API metadata, business object scope, integration scenarios, payload validation and mapping to SAP IS-U/FI-CA objects.",
    ),
    _expert_topic(
        "s4-cloud-integration",
        "S/4HANA Utilities / Fiori / API",
        "Cloud Integration for Utilities",
        "SAP S/4HANA Utilities cloud integration BTP market communication API",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "API", "EDIFACT"),
        "Cloud integration topics help connect S/4HANA Utilities, BTP, integration flows, APIs and market communication interfaces.",
    ),
    _expert_topic(
        "s4-simplification",
        "S/4HANA Utilities / Fiori / API",
        "S/4HANA Utilities Simplification and Migration",
        "SAP S/4HANA Utilities simplification migration IS-U data model Fiori API",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "ISU", "FIORI", "API"),
        "Simplification and migration topics help distinguish classic IS-U behavior from S/4HANA Utilities changes in UI, APIs, compatibility, custom code and operations.",
    ),
    _expert_topic(
        "country-netherlands",
        "Country Market Rules",
        "Netherlands Utilities Market Rules",
        "SAP IS-U Netherlands utilities market communication rules supplier switch meter reading",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Country-specific rules for the Netherlands should be validated against local regulator/network operator documentation and SAP localization notes. The KB topic is a starting point for market process and data exchange research.",
    ),
    _expert_topic(
        "country-united-kingdom",
        "Country Market Rules",
        "United Kingdom Utilities Market Rules",
        "SAP IS-U United Kingdom utilities market communication smart metering settlement",
        ("uregni-retail", "sap-help", "sap-community-utilities"),
        ("ISU", "EDIFACT", "API"),
        "United Kingdom utilities topics should connect local market rules, supplier switching, smart metering, settlement and SAP localization/integration evidence from official sources.",
    ),
    _expert_topic(
        "country-spain",
        "Country Market Rules",
        "Spain Utilities Market Rules",
        "SAP IS-U Spain utilities market communication switching meter reading billing",
        ("cnmc-spain", "sap-help", "sap-community-utilities"),
        ("ISU", "EDIFACT", "API"),
        "Spain utilities topics should be validated against official market operator/regulator material and SAP localization sources before being used as final guidance.",
    ),
    _expert_topic(
        "country-france",
        "Country Market Rules",
        "France Utilities Market Rules",
        "SAP IS-U France utilities market communication supplier switch meter reading",
        ("cre-france", "sap-help", "sap-community-utilities"),
        ("ISU", "EDIFACT", "API"),
        "France utilities topics should map local market communication and distribution/supplier processes to SAP IS-U master data, meter reading, billing and integration objects.",
    ),
    _expert_topic(
        "country-italy",
        "Country Market Rules",
        "Italy Utilities Market Rules",
        "SAP IS-U Italy utilities market communication switching billing meter reading",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Italy utilities topics should capture country process terminology, official market documentation, SAP localization evidence and integration touchpoints.",
    ),
    _expert_topic(
        "country-austria-switzerland",
        "Country Market Rules",
        "Austria and Switzerland Utilities Rules",
        "SAP IS-U Austria Switzerland utilities market communication supplier switch billing",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Austria and Switzerland topics should separate local rules from German MaKo assumptions and trace official source evidence for SAP IS-U process mapping.",
    ),
    _expert_topic(
        "country-belgium-nordics",
        "Country Market Rules",
        "Belgium and Nordic Utilities Rules",
        "SAP IS-U Belgium Nordics utilities market communication meter reading settlement",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Belgium and Nordic utilities topics should focus on official market process references, settlement/metering differences and SAP integration implications.",
    ),
    _expert_topic(
        "country-central-eastern-europe",
        "Country Market Rules",
        "Central and Eastern Europe Utilities Rules",
        "SAP IS-U Poland Czech Portugal utilities market communication localization",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Central/Eastern Europe country topics should be treated as research starting points and enriched with official regulator/network operator evidence before approval.",
    ),
    _expert_topic(
        "customizing-invoicing-fica-transfer",
        "Customizing / SPRO",
        "Invoicing to FI-CA Transfer Customizing",
        "SAP IS-U invoicing FI-CA transfer customizing ERDK DFKKOP account determination",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "ERDK", "DFKKOP", "DFKKOPK"),
        "Invoicing-to-FI-CA transfer customizing is important when print documents, FI-CA postings, account determination or reconciliation do not match billing expectations.",
    ),
    _expert_topic(
        "customizing-move-in-out",
        "Customizing / SPRO",
        "Move-In / Move-Out Customizing",
        "SAP IS-U move-in move-out customizing contract start final billing EVER EANL",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("SPRO", "EVER", "EANL", "EC50E"),
        "Move-in/out customizing topics cover contract creation, final billing, meter reading requirements, account assignment and process control.",
    ),
    _expert_topic(
        "customizing-market-communication",
        "Customizing / SPRO",
        "Market Communication Customizing",
        "SAP IS-U IDE market communication customizing UTILMD MSCONS APERAK EDIDS",
        MAKO_SOURCES + TECH_SOURCES,
        ("SPRO", "UTILMD", "MSCONS", "APERAK", "EDIDS"),
        "Market communication customizing links IDoc setup, process identifiers, partner data, validation and process monitoring for utilities market exchange.",
    ),
    _expert_topic(
        "messages-move-in-out",
        "Messages / Errors",
        "Move-In / Move-Out Error Messages",
        "SAP IS-U move-in move-out error messages EC50E EVER EANL contract account",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("EC50E", "EVER", "EANL", "FKKVKP"),
        "Move-in/out message topics help connect failed customer lifecycle steps to missing master data, contract account settings, device allocation or final billing prerequisites.",
    ),
    _expert_topic(
        "messages-device-allocation",
        "Messages / Errors",
        "Device Allocation Error Messages",
        "SAP IS-U device allocation error messages EGERH EASTL ETDZ installation",
        TECH_SOURCES + ("sap-help", "michael-management-messages"),
        ("EGERH", "EASTL", "ETDZ", "EANL"),
        "Device allocation messages often require checking validity intervals, register facts, installation structure and billing-relevant time slices.",
    ),
    _expert_topic(
        "messages-api-fiori",
        "Messages / Errors",
        "Fiori / API Error Triage",
        "SAP S/4HANA Utilities Fiori API error troubleshooting OData authorization",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "FIORI", "API"),
        "Fiori/API error triage connects frontend messages to backend service calls, authorization, payload validation and SAP business object state.",
    ),
    _expert_topic(
        "abap-bapi-utilities",
        "ABAP / Enhancements",
        "BAPIs and Released APIs",
        "SAP IS-U BAPI function module utilities integration contract account meter reading",
        ("sap-help", "sap-business-accelerator-hub", "se80", "tcodesearch"),
        ("BAPI", "SE37", "API", "FKKVKP", "EABL"),
        "BAPI/API topics help compare classic ABAP function module integration with released APIs and identify where custom integrations should be validated.",
    ),
    _expert_topic(
        "abap-debugging-update-tasks",
        "ABAP / Enhancements",
        "Debugging Update Tasks and Background Processing",
        "SAP IS-U ABAP debugging update task background job billing IDoc FI-CA",
        ("sap-help", "se80", "sap-datasheet"),
        ("SE80", "SE37", "EDIDS", "ERCH", "DFKKOP"),
        "Debugging and update task topics support incidents where data changes occur asynchronously through background jobs, update tasks, IDoc processing or FI-CA mass activities.",
    ),
    _expert_topic(
        "abap-custom-code-atc",
        "ABAP / Enhancements",
        "Custom Code and ATC for Utilities",
        "SAP S/4HANA Utilities custom code ATC ABAP enhancement migration",
        ("sap-help", "se80", "sap-community-utilities"),
        ("S4HANA", "SE80", "BADI"),
        "Custom code and ATC topics help evaluate legacy IS-U enhancements during S/4HANA migration or regression analysis.",
    ),
    _expert_topic(
        "runbook-background-jobs",
        "Runbooks / Troubleshooting",
        "Background Jobs and Mass Activities",
        "SAP IS-U troubleshooting background jobs mass activities billing invoicing FI-CA IDoc",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("ERCH", "ERDK", "DFKKOP", "EDIDS"),
        "Background job runbooks connect scheduled mass processing, job logs, application logs, locks, IDoc queues and downstream business document state.",
    ),
    _expert_topic(
        "runbook-authorization",
        "Runbooks / Troubleshooting",
        "Authorization Troubleshooting",
        "SAP IS-U authorization troubleshooting Fiori transaction SU53 business role",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("FIORI", "S4HANA", "BP", "FPL9"),
        "Authorization runbooks separate missing display/change rights, business roles, Fiori catalogs, transaction access and backend object checks.",
    ),
    _expert_topic(
        "runbook-performance",
        "Runbooks / Troubleshooting",
        "Performance and Volume Troubleshooting",
        "SAP IS-U performance troubleshooting billing meter reading FI-CA IDoc mass data",
        OFFICIAL_SOURCES + TECH_SOURCES,
        ("EABL", "ERCH", "DFKKOP", "EDIDS"),
        "Performance topics cover high-volume utilities processing, slow searches, mass runs, large IDoc batches and where to capture evidence before changing logic.",
    ),
    _expert_topic(
        "s4-cds-analytics",
        "S/4HANA Utilities / Fiori / API",
        "CDS Views and Embedded Analytics",
        "SAP S/4HANA Utilities CDS views embedded analytics Fiori billing contract account",
        OFFICIAL_SOURCES,
        ("S4HANA", "FIORI", "API"),
        "CDS/analytics topics connect operational SAP IS-U data to S/4HANA reporting, app tiles, authorization and traceability requirements.",
    ),
    _expert_topic(
        "s4-odata-authorizations",
        "S/4HANA Utilities / Fiori / API",
        "OData Services and Authorizations",
        "SAP S/4HANA Utilities OData services authorization Fiori API troubleshooting",
        OFFICIAL_SOURCES + ("sap-community-utilities",),
        ("S4HANA", "FIORI", "API"),
        "OData authorization topics help diagnose Fiori/API failures where service activation, roles, catalogs or backend business object checks are involved.",
    ),
    _expert_topic(
        "country-ireland",
        "Country Market Rules",
        "Ireland Utilities Market Rules",
        "SAP IS-U Ireland utilities market communication supplier switching metering settlement",
        ("ireland-rmd", "sap-help", "sap-community-utilities"),
        ("ISU", "EDIFACT", "API"),
        "Ireland utilities topics should be enriched with official local market documentation and mapped to SAP IS-U master data, meter reading and settlement processes.",
    ),
    _expert_topic(
        "country-denmark-cliaden",
        "Country Market Rules",
        "Denmark and Sweden Utilities Rules",
        "SAP IS-U Denmark Sweden utilities market communication metering supplier switch",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Denmark and Sweden topics should capture local hub, supplier switch, metering and settlement requirements separately from German MaKo assumptions.",
    ),
    _expert_topic(
        "country-greece-cyprus",
        "Country Market Rules",
        "Greece and Cyprus Utilities Rules",
        "SAP IS-U Greece Cyprus utilities market communication billing metering localization",
        COUNTRY_SOURCES + ("sap-community-utilities",),
        ("ISU", "EDIFACT", "API"),
        "Greece and Cyprus topics should be treated as regulated-market research seeds and validated against local utility, regulator and SAP localization sources.",
    ),
)


TOPIC_CATALOG: tuple[TopicDefinition, ...] = (
    CURATED_TOPIC_CATALOG + SCOUT_TOPIC_CATALOG + EXPERTISE_TOPIC_CATALOG
)


def list_topic_catalog(category: str | None = None) -> list[TopicDefinition]:
    if not category:
        return list(TOPIC_CATALOG)
    category_norm = category.strip().lower()
    return [topic for topic in TOPIC_CATALOG if topic.category.lower() == category_norm]


def pick_catalog_topics(seed_queries: list[str] | None = None, limit: int | None = None) -> list[TopicDefinition]:
    """Pick a broad, query-aware topic set without always taking the catalog head."""
    topics = list(TOPIC_CATALOG)
    max_count = len(topics) if limit is None else max(1, min(int(limit), len(topics)))
    query_text = " ".join(seed_queries or []).lower()
    if not query_text:
        return _round_robin_by_category(topics, max_count)

    scored: list[tuple[int, int, TopicDefinition]] = []
    unscored: list[TopicDefinition] = []
    for idx, topic in enumerate(topics):
        score = _topic_score(topic, query_text)
        if score:
            scored.append((score, idx, topic))
        else:
            unscored.append(topic)
    picked: list[TopicDefinition] = []
    scored_buckets: dict[str, list[tuple[int, int, TopicDefinition]]] = {}
    for score, idx, topic in sorted(scored, key=lambda row: (-row[0], row[1])):
        scored_buckets.setdefault(topic.category, []).append((score, idx, topic))
    category_order = sorted(
        scored_buckets,
        key=lambda category: (-scored_buckets[category][0][0], category),
    )
    while len(picked) < max_count and any(scored_buckets.values()):
        for category in category_order:
            if scored_buckets[category]:
                picked.append(scored_buckets[category].pop(0)[2])
                if len(picked) >= max_count:
                    break
    for topic in _round_robin_by_category(unscored, len(topics)):
        if topic not in picked:
            picked.append(topic)
        if len(picked) >= max_count:
            break
    return picked[:max_count]


def _topic_score(topic: TopicDefinition, query_text: str) -> int:
    searchable = " ".join(
        [
            topic.category,
            topic.label,
            topic.topic,
            topic.seed_text,
            " ".join(topic.objects),
        ]
    ).lower()
    score = 0
    for obj in topic.objects:
        if obj.lower() in query_text:
            score += 6
    for phrase in (topic.category, topic.label):
        if phrase.lower() in query_text:
            score += 4
    for token in {t for t in query_text.replace("/", " ").replace("-", " ").split() if len(t) > 2}:
        if token in searchable:
            score += 1
    return score


def _round_robin_by_category(topics: list[TopicDefinition], limit: int) -> list[TopicDefinition]:
    buckets: dict[str, list[TopicDefinition]] = {}
    for topic in topics:
        buckets.setdefault(topic.category, []).append(topic)
    ordered: list[TopicDefinition] = []
    while len(ordered) < limit and any(buckets.values()):
        for category in sorted(buckets):
            if buckets[category]:
                ordered.append(buckets[category].pop(0))
                if len(ordered) >= limit:
                    break
    return ordered


def find_topic_definition(topic_text: str) -> TopicDefinition | None:
    text = (topic_text or "").strip().lower()
    for topic in TOPIC_CATALOG:
        if topic.topic.lower() == text or topic.id.lower() == text:
            return topic
    for topic in TOPIC_CATALOG:
        if all(obj.lower() in text for obj in topic.objects[:1]):
            return topic
    return None
